### ISSUE TITLE
Implement React boilerplate.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/etymology-scraper#1]
# Motivation

Before starting the project, the React boilerplate must be created.

# Tasks

- [x] Install React boilerplate.
- [x] Integrate browserify.
- [x] Create a public directory to serve as static middleware:
    - [x] Index.html with links to bundle file and stylesheet.
